'use client';

import { useState, useCallback, useRef, useEffect } from 'react';
import { sendChat, clearHistory } from '@/lib/api';
import type { Message } from '@/lib/types';

//Generates a random hex session ID (32 chars, like Python's uuid4().hex).
function generateSessionId(): string {
  return crypto.randomUUID().replaceAll('-', '');

  // older browser compatibility and LAN compatibility if needed
  // const bytes = new Uint8Array(16);
  // crypto.getRandomValues(bytes);
  // return Array.from(bytes)
  //   .map((b) => b.toString(16).padStart(2, "0"))
  //   .join("");
}

const SESSION_KEY = 'privacy_chatbot_session_id';

//Gets or creates a persistent session ID from localStorage.
function getOrCreateSessionId(): string {
  const stored = localStorage.getItem(SESSION_KEY);
  if (stored) return stored;

  const newId = generateSessionId();
  localStorage.setItem(SESSION_KEY, newId);
  return newId;
}

export function useChat() {
  const [messages, setMessages] = useState<Message[]>([]);
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [sessionId, setSessionId] = useState<string>('');

  useEffect(() => {
    // eslint-disable-next-line
    setSessionId(getOrCreateSessionId()); //ignore linter error its allowed and recommended
  }, []);

  const abortRef = useRef<AbortController | null>(null);

  //Sends a message and gets the AI response.
  const sendMessage = useCallback(
    async (query: string) => {
      if (!query.trim() || isLoading) return;

      setError(null);

      // Add human message immediately
      const humanMsg: Message = {
        id: `human-${Date.now()}`,
        role: 'human',
        content: query.trim(),
        timestamp: Date.now(),
      };
      setMessages((prev) => [...prev, humanMsg]);
      setIsLoading(true);

      try {
        const response = await sendChat(query.trim(), sessionId);

        if (response.success && response.data) {
          const aiMsg: Message = {
            id: `ai-${Date.now()}`,
            role: 'ai',
            content: response.data.answer,
            sources: response.data.sources,
            responseTimeMs: response.data.response_time_ms,
            timestamp: Date.now(),
          };
          setMessages((prev) => [...prev, aiMsg]);

          // Update session ID if it was auto-generated by backend
          if (
            response.data.session_id &&
            response.data.session_id !== sessionId
          ) {
            setSessionId(response.data.session_id);
            localStorage.setItem(SESSION_KEY, response.data.session_id);
          }
        } else {
          setError(response.error || 'Failed to get response from AI.');
          // Remove the human message on error
          setMessages((prev) => prev.filter((m) => m.id !== humanMsg.id));
        }
      } catch {
        setError('Network error. Is the API server running?');
        setMessages((prev) => prev.filter((m) => m.id !== humanMsg.id));
      } finally {
        setIsLoading(false);
      }
    },
    [isLoading, sessionId]
  );

  //Starts a new chat session — clears messages and generates new session ID.
  const startNewChat = useCallback(async () => {
    // Clear history on the backend
    if (sessionId) {
      try {
        await clearHistory(sessionId);
      } catch {
        // Silent fail — local state will be cleared regardless
      }
    }

    // Reset local state
    setMessages([]);
    setError(null);

    // Generate new session
    const newId = generateSessionId();
    setSessionId(newId);
    localStorage.setItem(SESSION_KEY, newId);
  }, [sessionId]);

  //Cancels any ongoing request (for future streaming support).
  const cancelRequest = useCallback(() => {
    if (abortRef.current) {
      abortRef.current.abort();
      abortRef.current = null;
    }
    setIsLoading(false);
  }, []);

  return {
    messages,
    isLoading,
    error,
    sessionId,
    sendMessage,
    startNewChat,
    cancelRequest,
    setError,
  };
}
