"""
Persistent session management using SQLite.

Stores per-session chat history so it survives server restarts.
No login required — sessions are identified by anonymous UUIDs
generated by the frontend or auto-created by the backend.

SQLite is chosen because:
- Zero external dependencies (built into Python)
- Data stays local (privacy-first)
- No Redis/Postgres needed for a single-server deployment
"""

import logging
import sqlite3
from datetime import UTC, datetime

from langchain_core.messages import AIMessage, HumanMessage

from app.config import settings

logger = logging.getLogger(__name__)


class SessionService:
    """
    Manages per-user conversation sessions with persistent SQLite storage.

    Each session_id maps to an ordered list of chat messages (human + AI).
    History is trimmed to MAX_HISTORY_TURNS per session to keep prompts
    within the LLM context window.
    """

    def __init__(self):
        self.db_path = settings.DB_DIR / "chat_sessions.db"

        # Ensure the parent directory exists
        self.db_path.parent.mkdir(parents=True, exist_ok=True)

        self._init_db()

    def _init_db(self) -> None:
        """Creates the chat_messages table if it doesn't exist."""
        with self._get_connection() as conn:
            conn.execute("""
                CREATE TABLE IF NOT EXISTS chat_messages (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    session_id TEXT NOT NULL,
                    role TEXT NOT NULL CHECK(role IN ('human', 'ai')),
                    content TEXT NOT NULL,
                    created_at TEXT NOT NULL DEFAULT (datetime('now'))
                )
            """)
            conn.execute(
                "CREATE INDEX IF NOT EXISTS idx_session_id "
                "ON chat_messages(session_id)"
            )
            conn.execute(
                "CREATE INDEX IF NOT EXISTS idx_session_created "
                "ON chat_messages(session_id, created_at)"
            )
        logger.info(f"Session database initialized at: {self.db_path}")

    def _get_connection(self) -> sqlite3.Connection:
        """Returns a new SQLite connection with row factory enabled."""
        conn = sqlite3.connect(self.db_path)
        conn.row_factory = sqlite3.Row
        return conn

    def get_history(self, session_id: str) -> list[HumanMessage | AIMessage]:
        """
        Retrieves the most recent conversation history for a session.
        Returns LangChain message objects for direct use in prompts.
        Respects MAX_HISTORY_TURNS limit (returns last N turns).
        """
        max_messages = settings.MAX_HISTORY_TURNS * 2

        with self._get_connection() as conn:
            # Get the last N messages in chronological order
            rows = conn.execute(
                """
                SELECT role, content FROM (
                    SELECT role, content, created_at
                    FROM chat_messages
                    WHERE session_id = ?
                    ORDER BY created_at DESC, id DESC
                    LIMIT ?
                ) sub ORDER BY created_at ASC, id ASC
                """,
                (session_id, max_messages),
            ).fetchall()

        messages = []
        for row in rows:
            if row["role"] == "human":
                messages.append(HumanMessage(content=row["content"]))
            else:
                messages.append(AIMessage(content=row["content"]))

        return messages

    def append_to_history(
        self, session_id: str, human_content: str, ai_content: str
    ) -> None:
        """
        Saves a human-AI message pair to the session history.
        Both messages are stored with the same timestamp for pairing.
        """
        now = datetime.now(UTC).isoformat()

        with self._get_connection() as conn:
            conn.executemany(
                "INSERT INTO chat_messages (session_id, role, content, created_at) "
                "VALUES (?, ?, ?, ?)",
                [
                    (session_id, "human", human_content, now),
                    (session_id, "ai", ai_content, now),
                ],
            )

    def clear_session(self, session_id: str) -> int:
        """
        Deletes all messages for a session.
        Returns the number of messages deleted.
        """
        with self._get_connection() as conn:
            cursor = conn.execute(
                "DELETE FROM chat_messages WHERE session_id = ?",
                (session_id,),
            )
            deleted = cursor.rowcount

        if deleted > 0:
            logger.info(
                f"Cleared session {session_id}: {deleted} messages deleted"
            )
        else:
            logger.info(f"Session {session_id} had no messages to clear")

        return deleted

    def session_exists(self, session_id: str) -> bool:
        """Checks if a session has any stored messages."""
        with self._get_connection() as conn:
            row = conn.execute(
                "SELECT 1 FROM chat_messages WHERE session_id = ? LIMIT 1",
                (session_id,),
            ).fetchone()
        return row is not None

    def get_all_sessions(self) -> list[dict]:
        """
        Returns a summary of all active sessions.
        Useful for admin/debug purposes.
        """
        with self._get_connection() as conn:
            rows = conn.execute(
                """
                SELECT
                    session_id,
                    COUNT(*) as message_count,
                    MIN(created_at) as first_message,
                    MAX(created_at) as last_message
                FROM chat_messages
                GROUP BY session_id
                ORDER BY last_message DESC
                """
            ).fetchall()

        return [
            {
                "session_id": row["session_id"],
                "message_count": row["message_count"],
                "first_message": row["first_message"],
                "last_message": row["last_message"],
            }
            for row in rows
        ]


# Singleton instance
session_service = SessionService()
